### ISSUE TITLE
You aren't in a party,

### ISSUE THREAD

**Issue by SubbyDK** [Wuild/GatherLite#129] opened 2020-01-02 13:33 UTC
When in BG the addon make a lot of "You aren't in a party" spam.
Full up to date.
All other addons disabled.

**Comment by gotmilk0112** [comment] 2020-01-25 23:31
I get this too. No matter what settings I select in GatherLite, it just spams me with "You are not in a party." when I'm in a BG.

**Comment by d3aths** [comment] 2020-02-14 06:53
yeah, would be good at have a fix for this. the spam is really bad. it spams literally once every 2 seconds. had to disable the addon and now using another because of this issue

**Comment by cro0sh** [comment] 2020-03-16 12:22
Temp "fix": Hover over chat, click general -> settings -> other on left -> turn off System Messages top right.

**Comment by fournierj** [comment] 2020-04-08 20:12
This seems to be caused by the version check functionality. In GatherLite/GatherLite.lua, on line 81, an event gets registered to call SendVersionCheck every 5 seconds.  If you comment this out (-- at the start of the line), it will fix the issue. 

I see this in groups that are not parties - specifically Horrific Visions. In GatherLite/scripts/methods.lua, on line 743, the version is sent to the PARTY channel. I think the Horrific Vision puts you in a group, but it's not an actual party if you're there solo and the party chat isn't active, causing the error message "You aren't in a party".

**Comment by oddtoddy** [comment] 2020-04-09 00:13
> This seems to be caused by the version check functionality. In GatherLite/GatherLite.lua, on line 81, an event gets registered to call SendVersionCheck every 5 seconds. If you comment this out (-- at the start of the line), it will fix the issue.
> 
> I see this in groups that are not parties - specifically Horrific Visions. In GatherLite/scripts/methods.lua, on line 743, the version is sent to the PARTY channel. I think the Horrific Vision puts you in a group, but it's not an actual party if you're there solo and the party chat isn't active, causing the error message "You aren't in a party".

This seems to fix it for most of the game, but when I go into an instanced dungeon, it starts doing it again.

**Comment by fournierj** [comment] 2020-04-09 12:59
Strange. Can you give me more details please? I can't reproduce this. Are you in a party when you go in the instance? Which instance is it? In your GatherLite settings do you have the p2pnodes settings for Guild or Party turned on or off?

**Comment by Wuild** [comment] 2020-04-09 15:14
This has been fixed in 3.0.0-alpha. Available for download now.

**Closed as completed by Wuild** 2020-04-09 15:14 UTC

**Comment by oddtoddy** [comment] 2020-04-09 22:08
Is this addon only for Classic now? I don't see any 8.3 version of the new alpha.

**Comment by fournierj** [comment] 2020-04-10 01:43
Still occurring for me in 3.0.0-alpha

**Comment by GeoHolz** [comment] 2020-04-22 12:50
Yep not fixed with latest version
